#!/usr/bin/env bash

set -euo pipefail

frontend_path="$(dirname "$(realpath "$0")")/frontend"

# first restore frontend/public to prevoius revision
git restore --source=HEAD --staged --worktree -- "$frontend_path/public"

if [ "$(git branch --show-current)" = "main" ] && [ -z "$(git status --porcelain)" ]; then
  echo "Ready to deploy, branch is main and working tree is clean..."
else
  echo "Cannot deploy, branch is not main or working tree has changes."
  exit 1
fi

$(./build-css && cd "$frontend_path" && zola build --base-url "https://ryanwild.github.io/kidshub_web/")

git add "$frontend_path/public"
git commit -m "Deployment: $(git rev-parse --verify HEAD)"
git push origin

# git switch main
git subtree split --prefix "frontend/public" -b gh-pages # create a local gh-pages branch containing the splitted output folder
git push -f origin gh-pages:gh-pages                     # force the push of the gh-pages branch to the remote gh-pages branch at origin
git branch -D gh-pages                                   # delete the local gh-pages because you will need it: ref
