services:
  frontend:
    build:
      context: "./frontend/"
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test:
        ["CMD", "curl", "-f", "https://kidshub.local/health", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  caddy_data:
  caddy_config:
